export enum LanguageType {
    ENGLISH = "English",
    SPANISH = "Spanish",
    FRENCH = "French",
    GERMAN = "German",
    CHINESE = "Chinese",
    JAPANESE = "Japanese",
    HINDI = "Hindi",
    ARABIC = "Arabic",
    RUSSIAN = "Russian",
    PORTUGUESE = "Portuguese",
    ITALIAN = "Italian",
    KOREAN = "Korean",
    DUTCH = "Dutch",
    SWEDISH = "Swedish",
    NORWEGIAN = "Norwegian",
    DANISH = "Danish",
    FINNISH = "Finnish",
    POLISH = "Polish",
    TURKISH = "Turkish",
    GREEK = "Greek",
    HEBREW = "Hebrew",
    VIETNAMESE = "Vietnamese",
    THAI = "Thai",
    INDONESIAN = "Indonesian",
    MALAY = "Malay",
    FILIPINO = "Filipino",
  }